# Generated by Django 3.1.5 on 2021-02-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField(default=1, help_text=' en dólares')),
                ('peso', models.PositiveIntegerField(help_text=' en libras')),
                ('tipo', models.CharField(choices=[('Virtual', 'Virtual'), ('Físico', 'Físico')], default='Físico', max_length=7)),
                ('url_download', models.URLField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
