# Generated by Django 3.1.5 on 2021-02-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_libro'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='libro',
            unique_together={('nombre', 'tipo')},
        ),
    ]
