# Generated by Django 3.1.5 on 2021-03-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_viewpadrehijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoNombre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nuevo_nombre',
            },
        ),
    ]
