# Generated by Django 3.1.5 on 2021-03-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_nuevonombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevonombre',
            name='a',
            field=models.CharField(db_column='otro_nombre', default='', max_length=50),
        ),
    ]
