# Generated by Django 3.1.5 on 2021-03-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_nuevonombre_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(default='', max_length=60),
        ),
    ]
